main: main.o
	g++ main.o -L./lib -lsprite -lGL -lGLEW -lglfw -lSOIL -lGLC -I./include -o main

run: main.cpp
	/media/rounak/DATA/data/lectures_and_stuffs/CS293/Graph_Stimulator/Code/simplecpp/s++ main.cpp